plugins {
    id 'com.android.application'
}

android {
    namespace 'com.jlr.jacobmaps'
    compileSdk 34

    defaultConfig {
        applicationId "com.jlr.jacobmaps"
        minSdk 31
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release { minifyEnabled false }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
    implementation 'org.maplibre.gl:android-sdk:11.5.2'
}
